name: Demo

on: [push]

jobs:
  demo:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Hello
        run: |
          echo "Hello from Kubernetes!"
          hostname
          pwd
